[project]
name = "dawgi-marimo-talk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "astropy>=7.0.1",
    "marimo[extras,recommended]>=0.11.0",
    "matplotlib>=3.10.0",
    "seaborn>=0.13.2",
]
